%{
############################
STRUCTURE 

Intro 
- 8 * 4/4 guitare1 [1 - 8]
- 8 * 4/4 guitare1 guit2 drums [9 - 16]
- 8 * 4/4 + basse [17 - 24]

Verse [25 - 40] chant

Chorus [41 - 46] chant

Re-intro [47 - 54] instrumental

Verse [55 - 70] chant

Chorus [71 - 76] chant

Re-intro [77 - 84] instrumental

Solo guitare [85 - 108] instrumental

Re-intro [105 - 112] instrumental

Verse [113 - 128] chant

Chorus [129 - 134] chant

Outro [135 - 150] = 2 x Re-intro

Fade Out [151 - 163] = x Re-intro + impro

#############################
PAROLES
V1
We all came out to Montreux
On the Lake Geneva shoreline
To make records with a mobile, yeah
We didn't have much time now
Frank Zappa and the Mothers
Were at the best place around
But some stupid with a flare gun
Burned the place to the ground

Chorus
Smoke on the water, a fire in the sky
(Smoke) on the water, you guys are great

V2
They burned down the gambling house
It died with an awful sound
Funky Claude was running in and out
He was pulling kids out the ground now
When it all was over
Find another place
Swiss time was running out
It seemed that we would lose the race

Chorus
Smoke on the water, a fire in the sky
Smoke on the water

V3
Burn it down
We ended up at the Grand Hotel
It was empty, cold and bare
The Rolling truck Stones thing just outside
Huh, making our music there now
With a few red lights and a few old beds
We made a place to sweat
No matter what we get out of this
I know, I know we'll never forget

Chorus
Smoke on the water, a fire in the sky
Smoke on the water
%}


%test

%test2

%test3
%% Generated by lilypond-book
%% Options: [exampleindent=10.16\mm,indent=0\mm,line-width=160\mm,quote,ragged-right]
%\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************



\paper {
  indent = 0\mm
%  line-width = 160\mm
%  % offset the left padding, also add 1mm as lilypond creates cropped
%  % images with a little space on the right
%  line-width = #(- line-width (* mm  3.000000) (* mm 1))
%  line-width = 160\mm - 2.0 * 10.16\mm
%  % offset the left padding, also add 1mm as lilypond creates cropped
%  % images with a little space on the right
%  line-width = #(- line-width (* mm  3.000000) (* mm 1))
%  ragged-right = ##t
	score-markup-spacing = #'((basic-distance . 8)
         (minimum-distance . 1)
         (padding . 1))
}


\version "2.24.1"
%\title = "Smoke On The Water"
%\composer = "Deep Purple"

%\layout {
  
%}

guitareIntro = \chords {
	r2 
}

guitarePartieA = \chords {
	e1 a2 b2 e1 
	\time 3/4 
	a2 r4
	\time 4/4
	e1 e 
}

guitarePartieB = \chords {
	e1 e e b a2 b e a1 a1 a4 r2. r1 b1
}

guitarePartieC = \chords {
	\time 4/4
	r1 r1 r1 r1 |
	\bar "||"
	\break
}

guitareOutro = \chords {
        
	
	e1 a2 b2 e1 
	\time 3/4 
	a2 r4 
}


basseIntro = \relative {
  %Intro

  \set TabStaff.minimumFret = #0
  \set TabStaff.restrainOpenStrings = ##t
  \repeat percent 8 {r1} |
  \repeat percent 7 {r1} | r2 r8 e,, f fis |
  g-. g-. g-. g-. g-. g-. g-. g-. | g-. g-. g-. g-. g-. g-. g-. g-. | g-. g-. g-. g-. c-. c-. c-. b~ | b b g-. g-. g-. g-. f fis |
  g-. g-. g-. g-. g-. g-. g-. g-. | g-. g-. g-. g-. g-. g-. g-. g-. | g-. g-. g-. g-. c-. c-. c-. b~ | b b g-. g-. g-. g-. f fis |
  \break
}

bassePartieA = \relative {	
	%PartieA
	\set TabStaff.minimumFret = #0
	\set TabStaff.restrainOpenStrings = ##t	
	\time 4/4
	g,,8 g g4' g,8 g g4' | g,8 g g' b,~b c4 d8 |
	a,8 a r4 b8 b r16 g'8.|
	e8 e r4 e8 e r16 g8.|
	\time 3/4
	a,8 a r4 b8 e, |
	\time 4/4
	e'4 r2. |
	e8 e r4 e16 d b r a g8. |
	\bar "||"
	\break
}

bassePartieB = \relative {
	
	\set TabStaff.minimumFret = #0
	\set TabStaff.restrainOpenStrings = ##t	
	e,,8 e r2. |
	e'8 e r4 e16 d b r a g8. |
	e8 e r2. |
	b'8 b r4 e16 d b r a g8. |
	a8 a r4 b8 b r4 |
	\time 2/4
	e8 e r4 |
	\time 4/4
	a,1~|a~|a4 r2. | r1 |
	b8^\markup "4.x tacet" b b b b b b b |
	\bar "||"
	\break
}

bassePartieC = \relative {
	
	\time 4/4
	r1 r1 r1 r1 |
	\bar "||"
	\break
}

basseOutro = \relative {
	
	%Outro
	\set TabStaff.minimumFret = #0
	\set TabStaff.restrainOpenStrings = ##t
	\time 4/4
	e,8 e r4 e8 e r16 g8.|
	a,8 a r4 b8 b r16 g'8.|
	e8 e r4 e8 e r16 g8.|
	\time 3/4
	a,8 a r4 b8 e, |
	\bar "||"
}
	
\markup {Smoke On The Water / Deep Purple}
\markup {Structure : }
\markup {_}

\markup {Intro}
<<
  \new Voice \with {
  \omit StringNumber
  } 
  {
    \clef "bass_8"
    \time 4/4
    \basseIntro
  }
  %\guitareIntro
  \new TabStaff \with {
    stringTunings = #bass-tuning
  }
  {
    \basseIntro
  }
>>

\markup {Verse}
<<
  \new Voice \with {
    \omit StringNumber
  } 
  {
    \clef "bass_8"
    \time 4/4
    \bassePartieA
  }
  %\guitarePartieA
  \new TabStaff \with {
    stringTunings = #bass-tuning
  } 
  {
    \bassePartieA
  }
>>

\markup {Chorus}
<<
  \new Voice \with {
    \omit StringNumber
  } 
  {
    \clef "bass_8"
    \time 4/4
    \bassePartieB
  }
  %\guitarePartieB
  \new TabStaff \with {
    stringTunings = #bass-tuning
  }
  {
    \bassePartieB
  }
>>

\markup {Chorus (a capella)}
<<
	\new Voice \with {
		\omit StringNumber
	} 
	{
    \clef "bass_8"
	\time 4/4
    \bassePartieC
	}
	\guitarePartieC
	\new TabStaff \with {
		stringTunings = #bass-tuning
	} 
	{
    \bassePartieC
	}
>>

\markup {Chorus (3 reprises)}
<<
	\new Voice \with {
	\omit StringNumber
   } 
	{
    \clef "bass_8"
	\time 4/4
    \basseOutro
  }
  	\guitareOutro
  \new TabStaff \with {
    stringTunings = #bass-tuning
  } {
    \basseOutro
  }


>>


\pageBreak
\markup {I Love Rock'n Roll / Joan Jett}
\markup {Structure : I - C1 - V1 - C2 - V2 - C3 - V4(solo) - C4 (a capella) - C5 - C6 - C7}
\markup {_}

\markup {Intro}
upIntro = \drummode {
  \time 2/4
  
}
downIntro = \drummode {
  \time 2/4
  sn16 sn sn sn sn sn sn sn | \bar"||"
}
\new DrumStaff <<
  \new DrumVoice { \voiceOne \upIntro }
  \new DrumVoice { \voiceTwo \downIntro }
>>

\markup {Chorus : C1, C2, C3}
upChorus = \drummode {
  \time 4/4
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 |  
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  \time 3/4
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r |
  \time 4/4
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 |  
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  
}
downChorus = \drummode {
  \time 4/4
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  \time 3/4
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r | 
  \time 4/4
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 | \bar"||"
}
\new DrumStaff 
  \with {
    \consists Merge_rests_engraver}
<<
  \new DrumVoice { \voiceOne \upChorus }
  \new DrumVoice { \voiceTwo \downChorus }
>>

\markup {Verse : V1, V2, V3(solo Guitare) }
upVerse = \drummode {
  \time 4/4
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 |  
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  \time 2/4
  hhc16 r hhc16 r hhc16 r r8 |
  \time 4/4
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 |  
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 |  
  hhc16 r hhc16 r hhc16 r r8 hhc16 r hhc16 r hhc16 r r8 | 
  hhc16 r hhc16 r hhc16 r hhc16 r hhc16 r hhc16 r hhc16 r hhc16 r | 
  
}
downVerse = \drummode {
  \time 4/4
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  \time 2/4
  bd16 r bd16 r <<sn16 sn16>> r r8 | 
  \time 4/4
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  bd16 r bd16 r <<sn16 sn16>> r r8 bd16 r bd16 r <<sn16 sn16>> r r8 |
  <<bd16 sn16>> r r16 r <<bd16 sn16 sn16>> r r8 <<bd16 sn16>> r sn16 r <<bd16 sn16 sn16>> sn sn r16 |
  \bar"||"
}
\new DrumStaff 
  \with {
    \consists Merge_rests_engraver}
<<
  \new DrumVoice { \voiceOne \upVerse }
  \new DrumVoice { \voiceTwo \downVerse }
>>
